### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by jaypatelani** [thepowersgang/rust-barebones-kernel#15]
when i try to build i got first error regarding "make: x86_64-none-elf-as: Command not found" which  got around by changing makefile "make: x86_64-none-elf-as" to "make: x86_64-elf-as" but then got another one : http://termbin.com/bg8n

**Comment by thepowersgang** [comment]
The "command not found" I would call a documentation error, the makefile is written to look for `x86_64-none-elf` by default, which isn't documented in the readme.

The linked "error" (which would be better included inline) appears to not show any errors, can you confirm that there's no output from `rustc` here?

**Comment by jaypatelani** [comment]
Hello,
This is the full error i get : https://gist.github.com/jaypatelani/95d5d406f4a8e40cc9b91d3dce9a26a0

**Comment by thepowersgang** [comment]
Building libcore (and this kernel) _requires_ a nightly build of rustc (which enables use of feature flags).

According to these messages, you're using stable/beta.

**Comment by jaypatelani** [comment]
ah.. Thanks.. i thought i switched to nightly build. now it works. :+1:
