### ISSUE TITLE
Why use libcore

### ISSUE THREAD

**Issue by RobertWHurst** [thepowersgang/rust-barebones-kernel#7]
Just curious, why is it necessary to use libcore & rust nightly?

**Comment by thepowersgang** [comment]
Nightly is needed for `#![nostd]`, and libcore provides many useful features at next-to no cost. It's also needed for several language items, notably Sized and the ops traits.

These could be included in the source... yes, and I might make a branch for that. But libcore provides lots useful features that make rust what it is.
